language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - build-tools-29.0.2
    - android-29
    - extra-android-support
    - extra-android-m2repository
    - platform-tools
    - tools
  licenses:
    - 'android-sdk-license.*'
script: ./gradlew assembleRelease